### ISSUE TITLE
register/resetpass

### ISSUE THREAD

**Issue by conspyrosy** [liamjack/Auth#1]
Hey,

I don't know if this is obvious or not, but the in the class file, a few modifications need to be made when installing the class on a different domain. The $message_from variable should be changed, but most importantly, the domain in the verification link needs to be changed to the domain the script has been installed on. This needs to be done for the password reset function and the register function. 

Just wanted to point this out, as I was a bit puzzled after clicking a verification link, I ended up on your site.

**Comment by liamjack** [comment]
Thanks for reminding me about this, now the base url and from email address can be modified in config.php and work correctly :)
